-- 과목·단원 데이터만 시드 (문제, 태그, 사용자 제외)
DELETE FROM unit;
DELETE FROM subject;

INSERT INTO subject (id, name, created_at, updated_at) VALUES
(1, '전자계산기 구조론', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, '운영체제론', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, '데이터 통신론', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, '자료구조론', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, '데이터베이스론', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, '소프트웨어 공학론', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, '프로그래밍 언어론', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO unit (id, subject_id, name, unit_order, created_at, updated_at) VALUES
-- 과목 1: 전자계산기 구조론
(1, 1, '컴퓨터 시스템의 개요', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 1, '정보의 표현과 논리 회로', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 1, '논리 회로의 간소화 및 설계', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 1, '중앙처리장치(CPU)', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 1, '명령 실행과 제어', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 1, '기억장치', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 1, '입출력 시스템', 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 1, '고성능 컴퓨터 구조', 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- 과목 2: 운영체제론
(9, 2, '운영체제 개요', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 2, '프로세스 관리', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 2, 'CPU 스케줄링', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 2, '병행 프로세스와 동기화', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 2, '교착상태 (Deadlock)', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 2, '주기억장치 관리', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 2, '가상기억장치 관리', 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 2, '파일 시스템 및 디스크 관리', 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 2, '분산 운영체제 및 보안', 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- 과목 3: 데이터 통신론
(18, 3, '데이터 통신의 개요', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 3, '데이터 전송 기술', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 3, '통신 프로토콜과 OSI 7계층', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 3, '인터넷과 TCP/IP', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 3, '네트워크 보안 및 신기술', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- 과목 4: 자료구조론
(23, 4, '자료구조의 개요', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 4, '선형 구조', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, 4, '비선형 구조 1 (트리)', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 4, '비선형 구조 2 (그래프)', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 4, '정렬 (Sorting)', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 4, '검색 (Searching)', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- 과목 5: 데이터베이스론
(29, 5, '데이터베이스 개요', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 5, '데이터 모델링', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(31, 5, '관계 데이터 연산', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(32, 5, 'SQL', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(33, 5, '정규화', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 5, '데이터베이스 실무', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- 과목 6: 소프트웨어 공학론
(35, 6, '소프트웨어 공학 개요', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(36, 6, '프로젝트 관리', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(37, 6, '요구사항 분석 및 설계', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(38, 6, '객체지향 방법론', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 6, '소프트웨어 시험 및 유지보수', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- 과목 7: 프로그래밍 언어론
(40, 7, '프로그래밍 언어 개요', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(41, 7, '변수와 바인딩', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(42, 7, 'C언어', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(43, 7, 'JAVA', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(44, 7, '웹 프로그래밍 및 기타 언어', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
